Разметка главной страницы
htmlacademy-htmlcss/832991-technomart-29 pull request #2
Opened 2020-09-17 21:03 UTC by foontomas

Базовая вёрстка страницы с заготовками под слайдеры и без модальных окон.

2020-09-19 13:58 UTC, diana94 requested changes

2020-09-19 13:58 UTC, diana94 commented on index.html
> +      <section class="popular_vendors">
<img width="652" alt="HTML 1 : Техномарт 2020-09-19 16-02-25" src="https://user-images.githubusercontent.com/7550978/93667855-af82ac80-fa91-11ea-9d68-aaca3dd70b4f.png">
смотри, похоже, что два одинаковых блока с одинаковой шапкой, просто внутри два разных списка. кажется, что можно придумать им один класс и для шапок, соответсвенно, тоже. а списки обозвать по-разному `vendors-list` и `products-list`

2020-09-19 13:58 UTC, diana94 commented on index.html
> +          <li class="vendor-card bosch">
`vendor-card` достаточный класс для карточек, дополнительные bosch, makita И так далее можно удалить

2020-09-19 13:58 UTC, diana94 commented on index.html
> +      <section class="service-slider">
лучше назвать блок service, а внутри уже добавить блоки service-slider

2020-09-19 13:58 UTC, diana94 commented on index.html
> +          <div class="service-slider__slide service-slide1 service-slider__slide--default">
слайды лучше обернуть в `service-slider`
а это точно слайды? по дизайну больше похоже на табы
очень много классов, они также разного стиля
один точно можно убрать 

давай `service-slider__slide` назовем `service-slide`, а то внутри слайда очень много элементов, будет трудно называть

2020-09-19 13:58 UTC, diana94 commented on index.html
> +            <h2>
сюда бы добавить класс типа `service-slide__title`

2020-09-19 13:58 UTC, diana94 commented on index.html
> +            <p>
и сюда тоже

2020-09-19 13:58 UTC, diana94 commented on index.html
> +      <section class="description-contacts">
можно более общее название придумать, типа `company-info`

2020-09-19 13:58 UTC, diana94 commented on index.html
> +          <h2>
надо класс добавить. и для текста ниже тоже

2020-09-19 13:58 UTC, diana94 commented on index.html
> +          <h2>
надо класс добавить

2020-09-19 13:58 UTC, diana94 commented on index.html
> +      <div class="footer-1">
названия с цифрами не оч хорошее решение
хорошо, когда из названия можно информацию о блоке почерпнуть) даже footer-top более информативно 

можно попробовать одинаково обозвать и верхний и нижний блок в футоре и сделать модификатор для нижнего, чтобы его перекрасить (типа footer__section)

2020-09-19 13:58 UTC, diana94 commented on index.html
> +    <footer class="main-footer">
давай просто footer)

2020-09-19 13:58 UTC, diana94 commented on index.html
> +          <ul class="footer-nav-gold">
по сути такая же навигации как и выше, достаточно добавить модификатор `footer-nav footer-nav_gold`

2020-09-19 13:58 UTC, diana94 commented on index.html
> +            <a class="social-btn social-vk" href="#"></a>
это ссылки, ссылки лучше обзывать ссылками) и они вроде как идут в рамках именно social блока, так что лучший вариант social__link будет) модификаторы вроде как и не нужны для них, выглядят они одинаково

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +                  <a class="product-card__price" href="#">25500</a>
кажется, что карточка должна быть вся кликабельная, а не только ценник
лучше здесь заюзать тег <p>
а ниже добавить <a></a> и стиялми потом растянуть на всю карточку

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +            <ul class="catalog__pagination">
блок можно просто `pagination` назвать. тогда и `pagination__button` будет к месту. А так получается, что есть кнопка для блока pagination, а блока с таким классом нет

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +        <h2>
заголовки все одного стиля, можно сделать общий класс `title`

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +        <p>
`description__text`

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +          <ul class="footer-nav">
footer-nav в footer-navigation по смыслу как-то не очень
то есть навигация в навигации получается
`footer-navigation__row` или `footer-navigation__section` , ну и `_gold ` также добавить второму разделу

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +        <p>© 2010–2019 Компания «Техномарт»<br>
`footer__copyright`

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +            <a class="social__link social-vk" href="#"></a>
почему решил оставить social-vk ?
внутрь ссылочек надо картинки положить соц сетей будет

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +        <p class="footer-feedback">Обратная связь:
кажется, что feedback и dev находятся в одном блоке и является одинаковыми подблоками
я бы предложила их обернуть в что-то типа `footer-bottom__right-block`
а сами блоки обозвать `footer__info`

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +        <p class="header-declare">
два нижних подчеркивания, а не тире, это простой элемент хедера (или header-middle, как хочешь), а не самостоятельный блок

2020-10-03 10:46 UTC, diana94 commented on catalog.html
> +        <p class="header-address">
два нижних подчеркивания, а не тире, по той же причине что и declare

2020-10-03 10:46 UTC, diana94 commented on index.html
> +            <p class=product-card__old-price>
кавычки

2020-10-03 10:46 UTC, diana94 commented on index.html
> +          <input class="header-top__search" type="search" name="search" aria-label="Поле для поиска" placeholder="Поиск:">
класс достаточно на label повесить, на инпут не нужно

2020-10-03 10:46 UTC, diana94 commented on index.html
> +        <a class="header-middle__login" href="#">
здесь хорошо обозвал классами) а в catalog.html по-другому(

2020-10-03 10:46 UTC, diana94 commented on index.html
> +          <div class="highlight-card card-new highlight-card--yellow">
надо определиться, как будешь добавлять модификаторы:  `--` или `_`
кажется, что больше ты  используешь этот вариант `_`, давай на нем и остановимся)

2020-10-03 10:46 UTC, diana94 commented on index.html
> +            <p>
? `service-tab__text`

2020-10-03 10:46 UTC, diana94 commented on index.html
> +          <div class="service-tab service-tab1 service-tab--default">
`service-tab1 `- цифры в классе плохо
назови по смыслу таба лучше `service-tab_delivery`
service-tab--default - зачем нужен этот класс?

2020-10-03 10:46 UTC, diana94 commented on index.html
> +          <h2 class="index-h2">
общий класс для заголовка лучше так и назвать `title`
скорее всего будет ситуация, что и h3, h4 надо будет застилить под общий вид заголовков и тогда будет странно использовать `index-h2`

2020-10-10 21:16 UTC, foontomas commented on catalog.html
> +                  <a class="product-card__price" href="#">25500</a>
Сама карточка некликабельна, она реагирует на hover. Судя по описанию, кликабельным является наименование товара, скрытые ссылки-кнопки добавления товара в корзину и закладки. Поправил.

2020-10-10 21:18 UTC, foontomas commented on index.html
> +          <div class="service-tab service-tab1 service-tab--default">
Для вкладки по умолчанию. Но это ошибка, класс default должен стоять не на вкладке, а на кнопке, которая открывает вкладку. Поправил.

2020-10-10 21:19 UTC, foontomas commented on index.html
> +          <div class="highlight-card card-new highlight-card--yellow">
Мне где-то попались -- для модификаторов. Так и рисую. У тебя, кажется, в фаворитах одно нижнее подчёркивание.

2020-10-11 19:17 UTC, diana94 commented on catalog.html
> +                  <a class="product-card__price" href="#">25500</a>
да-да, ты прав, сорян

2020-10-11 19:24 UTC, diana94 commented on index.html
> +          <div class="highlight-card card-new highlight-card--yellow">
а, ну главное чтобы везде одинаково было)

2020-10-11 19:48 UTC, diana94 commented on index.html
> +          <div class="service-tab service-tab1 service-tab--default">
и на вкладке тоже, все правильно
кажется, что лучше дать общее название классу типа active, по которому стилизация будет кнопок и показываться нужный контент

2020-10-11 19:51 UTC, diana94 approved these changes

2020-10-11 19:51 UTC, diana94 commented on index.html
> +          <h2 class="section-headers h2-black">
зачем h2-black?

2020-10-11 19:51 UTC, diana94 commented on index.html
> +          <div class="service-tab service-tab-warranty">
давай вынесем service-tab-warranty и аналогичные service-tab-credit, service-tab-delivery в id. это уникальны штуки, которые нужны будут дальше для работы с js

2020-10-11 19:51 UTC, merged